server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/splitspend
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #any changes we make in the the entity, will be updated on the db: like new col addition, new validation
      #create-drop : will create schema on running the app, and will drop everything once teh app stops
    show-sql: true
    properties:
      hibernate:
        format_sql: true #formats the query in the logs: adding new line for each operation